// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcLcvKTMZhYE0vRFwippYDkhuNNThaXo',
    appId: '1:433558429730:web:0ac4112dfd9915d4ea6a7b',
    messagingSenderId: '433558429730',
    projectId: 'flutter-app-sandbox',
    authDomain: 'flutter-app-sandbox.firebaseapp.com',
    storageBucket: 'flutter-app-sandbox.firebasestorage.app',
    measurementId: 'G-J4QBNT1KC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcria2XQRlz_L_7pBL20Aor-qqThfOTB4',
    appId: '1:433558429730:android:d933756f9ae4bb3dea6a7b',
    messagingSenderId: '433558429730',
    projectId: 'flutter-app-sandbox',
    storageBucket: 'flutter-app-sandbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA065LcGGyhFfeohjjN0EyapixUJqFVYFw',
    appId: '1:433558429730:ios:dd273753e3f99250ea6a7b',
    messagingSenderId: '433558429730',
    projectId: 'flutter-app-sandbox',
    storageBucket: 'flutter-app-sandbox.firebasestorage.app',
    iosClientId: '433558429730-i6t8ubga2hgf7qjaa0oect9573hc1evh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA065LcGGyhFfeohjjN0EyapixUJqFVYFw',
    appId: '1:433558429730:ios:dd273753e3f99250ea6a7b',
    messagingSenderId: '433558429730',
    projectId: 'flutter-app-sandbox',
    storageBucket: 'flutter-app-sandbox.firebasestorage.app',
    iosClientId: '433558429730-i6t8ubga2hgf7qjaa0oect9573hc1evh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVcLcvKTMZhYE0vRFwippYDkhuNNThaXo',
    appId: '1:433558429730:web:011588501114639eea6a7b',
    messagingSenderId: '433558429730',
    projectId: 'flutter-app-sandbox',
    authDomain: 'flutter-app-sandbox.firebaseapp.com',
    storageBucket: 'flutter-app-sandbox.firebasestorage.app',
    measurementId: 'G-C26F62PPMZ',
  );
}
